export const IndustryCode = {
	'Sản xuất điện mặt trời': 'A',
	'Sản xuất nhiệt hoặc làm mát từ năng lượng mặt trời': 'A',
	'Sản xuất điện gió trên biển': 'A',
	'Sản xuất điện gió trong đất liền': 'A',
	'Sản xuất điện từ địa nhiệt': 'A',
	'Sản xuất nhiệt hoặc làm mát từ địa nhiệt': 'A',
	'Sản xuất điện từ năng lượng sinh học': 'A',
	'Sản xuất, chế biến, chế tạo nhiên liệu sinh học rắn': 'A',
	'Sản xuất, chế biến khí sinh học': 'A',
	'Sản xuất, chế biến, chế tạo nhiên liệu sinh học lỏng': 'A',
	'Sản xuất nhiệt hoặc làm mát từ năng lượng sinh học': 'A',
	'Sản xuất điện từ năng lượng tái tạo hải dương': 'A',
	'Xây dựng hệ thống đường dây, trạm biến áp để truyền tải, giải toả công suất năng lượng tái tạo': 'A',
	'Xây dựng, sửa chữa, nâng cấp hệ thống phân phối điện': 'A',
	'Lắp đặt, vận hành hệ thống, truyền tải, phân phối nhiên liệu khí bằng đường ống': 'A',
	'Lắp đặt, vận hành hệ thống lưu trữ điện từ năng lượng tái tạo': 'A',
	'Lắp đặt, vận hành hệ thống lưu trữ nhiệt năng từ năng lượng tái tạo': 'A',
	'Lắp đặt, vận hành hệ thống sản xuất, lưu trữ và phân phối năng lượng Hydrogen xanh': 'A',
	'Cải tạo, thay thế máy móc, thiết bị giúp sử dụng năng lượng tiết kiệm và hiệu quả': 'A',

	'Mua sắm phương tiện giao thông vận tải các-bon thấp': 'B',
	'Vận tải hàng hóa và hành khách bằng phương tiện các-bon thấp': 'B',
	'Phát triển cơ sở hạ tầng phục vụ giao thông vận tải các bon thấp': 'B',

	'Khai thác, xử lý và cung cấp nước sạch': 'C',
	'Quản lý chất lượng và bảo vệ nguồn nước': 'C',
	'Lắp đặt, vận hành hệ thống khử mặn nước biển và nước lợ': 'C',
	'Lắp đặt, vận hành hệ thống tiết kiệm tài nguyên nước': 'C',
	'Phát triển, lắp đặt, vận hành hệ thống tuần hoàn nước': 'C',
	'Lắp đặt, vận hành hệ thống thoát nước chống ngập úng': 'C',
	'Lắp đặt, vận hành hệ thống tưới tiêu thông minh': 'C',

	'Cải tạo, sửa chữa công trình xây dựng đạt mục tiêu công trình xanh': 'D',
	'Xây dựng mới công trình xanh': 'D',
	'Xây dựng, cải tạo công trình công ích  thân thiện với môi trường, ứng phó với biến đổi khí hậu, sử dụng hiệu quả tài nguyên thiên nhiên': 'D',

	'Trồng cây hàng năm và cây lâu năm theo tiêu chuẩn thực hành nông nghiệp tốt': 'E',
	'Ứng dụng mô hình chăn nuôi theo tiêu chuẩn thực hành nông nghiệp tốt': 'E',
	'Ứng dụng mô hình nông nghiệp xanh': 'E',
	'Ứng dụng mô hình nông nghiệp ứng dụng công nghệ cao': 'E',
	'Trồng rừng, phục hồi rừng, chăm sóc rừng, ươm giống cây lâm nghiệp; ngăn suy thoái rừng và phát triển các dịch vụ rừng đạt tiêu chuẩn quản lý rừng, môi trường quốc gia': 'E',
	'Khai thác, nuôi trồng thủy sản nội địa bền vững': 'E',
	'Khai thác, nuôi trồng thủy sản biển bền vững': 'E',
	'Phát triển sản phẩm nông, lâm, thủy và hải sản trong chuỗi cung ứng sản phẩm sạch': 'E',
	'Bảo tồn rừng': 'E',
	'Bảo tồn tài nguyên di truyền trong nông nghiệp bản địa': 'E',
	'Bảo vệ, duy trì và phát triển hệ sinh thái tự nhiên, phục hồi các hệ sinh thái bị suy thoái': 'E',
	'Du lịch sinh thái': 'E',
	'Bảo tồn nguồn gen và các loài động, thực vật quý hiếm, nguy cấp của Việt Nam': 'E',
	'Phát triển hạ tầng kỹ thuật phục vụ giảm nhẹ rủi ro và phòng chống thiên tai': 'E',
	'Canh tác bền vững trên vùng đất dốc, đất trũng, đất phèn, đất mặn, đất cát ven biển, đất có nguy cơ sa mạc hóa, hoang mạc hóa': 'E',
	'Xử lý ô nhiễm, cải tạo, phục hồi và bảo vệ tài nguyên đất': 'E',
	'Thu gom và xử lý chất thải chăn nuôi': 'E',
	'Xử lý phụ phẩm nông nghiệp trồng trọt': 'E',
	'Xử lý chất thải nuôi trồng thủy sản': 'E',

	'Sản xuất thiết bị điện và máy móc, thiết bị khác, sử dụng hiệu quả năng lượng': 'F',
	'Sản xuất linh kiện, thiết bị điện tử phục vụ phát triển công nghệ các-bon thấp': 'F',
	'Sản xuất phương tiện giao thông vận tải ứng dụng công nghệ các-bon thấp': 'F',
	'Sản xuất, cung cấp thiết bị, sản phẩm, công nghệ phục vụ yêu cầu bảo vệ môi trường': 'F',
	'Sản xuất linh kiện, thiết bị phục vụ sản xuất nhiên liệu Hydrogen và ứng dụng khác của công nghệ Hydrogen': 'F',

	'Phân loại chất thải rắn sinh hoạt hoặc chất thải rắn công nghiệp thông thường tại nguồn': 'G',
	'Thu gom, trung chuyển, vận chuyển chất thải rắn sinh hoạt hoặc chất thải rắn công nghiệp thông thường': 'G',
	'Tái sử dụng chất thải rắn': 'G',
	'Tái chế chất thải': 'G',
	'Xử lý chất thải rắn sinh hoạt và công nghiệp thông thường': 'G',
	'Thu gom, phân loại, xử lý chất thải nguy hại': 'G',
	'Thu gom nước thải đô thị, khu dân cư tập trung': 'G',
	'Xử lý nước thải đô thị, khu dân cư tập trung': 'G',
	'Thu gom, xử lý nước thải y tế': 'G',
	'Thu gom, xử lý nước thải từ hoạt động sản xuất, kinh doanh, dịch vụ': 'G',
	'Xử lý khí thải': 'G',

	'Xử lý dữ liệu, cho thuê hạ tầng thông tin và hoạt động liên quan': 'H',
	'Nghiên cứu khoa học, phát triển công nghệ, ứng dụng chuyển giao công nghệ về bảo vệ môi trường': 'H',
	'Tổ chức giáo dục, đào tạo và bồi dưỡng về bảo vệ môi trường': 'H',
	'Ứng dụng công nghệ thông tin trong bảo vệ môi trường, quản lý, sử dụng hiệu quả tài nguyên và ứng phó biến đổi khí hậu': 'H',
	'Sản xuất chương trình truyền hình, hoạt động điện ảnh về bảo vệ môi trường': 'H',
	'Hoạt động phát thanh, truyền hình về bảo vệ môi trường': 'H',
	'Dịch vụ hỗ trợ hoạt động bảo vệ môi trường, quản lý, sử dụng hiệu quả tài nguyên và ứng phó biến đổi khí hậu': 'H',
	'Dịch vụ hỗ trợ hoạt động tài chính cho bảo vệ môi trường': 'H',

	'Sản xuất điện từ nhiên liệu khí': 'I',
	'Sản xuất nhiệt hoặc làm mát từ nhiên liệu khí tự nhiên hoặc khí hoá lỏng (LNG)': 'I',
	'Chế biến sản phẩm thủy sản bền vững': 'I',
	'Sản xuất sắt, thép sử dụng hiệu quả năng lượng': 'I',
	'Sản xuất xi măng sử dụng hiệu quả năng lượng': 'I',
	other: 'I'
}
